kind: pipeline
type: docker
name: default

steps:
- name: wait-for-postgres
  image: postgres:16
  environment:
    POSTGRES_DB:
      from_secret: POSTGRES_DB
    POSTGRES_USER:
      from_secret: POSTGRES_USER
    POSTGRES_PASSWORD:
      from_secret: POSTGRES_PASSWORD
  commands:
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - while ! pg_isready -h postgres -d $POSTGRES_DB; do sleep 2; done
  - psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE SCHEMA IF NOT EXISTS workshop;"
  - psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "GRANT ALL ON SCHEMA workshop TO $POSTGRES_USER;"

- name: build
  image: maven:3.9-eclipse-temurin-21
  environment:
    AUTH0_CLIENT_ID:
      from_secret: AUTH0_CLIENT_ID
    AUTH0_CLIENT_SECRET:
      from_secret: AUTH0_CLIENT_SECRET
    AUTH0_ISSUER:
      from_secret: AUTH0_ISSUER
    WORKSHOP_CORS_ORIGINS:
      from_secret: WORKSHOP_CORS_ORIGINS
    POSTGRES_USER:
      from_secret: POSTGRES_USER
    POSTGRES_PASSWORD:
      from_secret: POSTGRES_PASSWORD
    POSTGRES_DB:
      from_secret: POSTGRES_DB
      
  commands:
  - export DATASOURCE_URL="jdbc:postgresql://postgres:5432/$POSTGRES_DB?user=$POSTGRES_USER&password=$POSTGRES_PASSWORD"
  - mvn clean test verify

trigger:
  branch:
    include:
      - feature/*
      - develop

services:
  - name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER:
        from_secret: POSTGRES_USER
      POSTGRES_PASSWORD:
        from_secret: POSTGRES_PASSWORD
      POSTGRES_DB:
        from_secret: POSTGRES_DB
