kind: pipeline
type: docker
name: default

steps:
- name: sleep
  image: busybox:latest
  commands:
  - sleep 5

- name: build
  image: maven:3.9-eclipse-temurin-21
  commands:
  - mvn clean test verify

trigger:
  branch:
    include:
      - feature/*
      - develop

services:
  - name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: drone
      POSTGRES_PASSWORD: drone
      POSTGRES_DB: drone
      