version: '3.7'
services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=${WORKSHOP_DB}'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '15432'
    
    volumes:
      - './docker/service-config:/docker-entrypoint-initdb.d'
