{{- if and .Values.secret.enabled (not .Values.secret.useExisting) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workshop-app.fullname" . }}
  labels:
    {{- include "workshop-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATASOURCE_URL: {{ .Values.secret.datasourceUrl | quote }}
  AUTH0_CLIENT_ID: {{ .Values.secret.auth0ClientId | quote }}
  AUTH0_CLIENT_SECRET: {{ .Values.secret.auth0ClientSecret | quote }}
{{- end }}
