name: Feature Branch Build

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: workshop
          POSTGRES_DB: workshop
          POSTGRES_PASSWORD: test

        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U workshop && break
            sleep 2
          done

      - name: Create custom schema
        run: |
          PGPASSWORD=test psql -h localhost -U workshop -d workshop -c "CREATE SCHEMA IF NOT EXISTS workshop;"
          PGPASSWORD=test psql -h localhost -U workshop -d workshop -c "ALTER SCHEMA workshop OWNER TO workshop;"

      - name: Build and Run Unit Tests
        env:
            DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
            AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
            AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
            AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }}
            WORKSHOP_CORS_ORIGINS: ${{ secrets.WORKSHOP_CORS_ORIGINS }}

        run: mvn clean test verify
