name: GitFlow Release

on:
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Execute GitFlow Release
        run: |
          mvn gitflow:release -DversionDigitToIncrement=1

      - name: Complete GitFlow Release
        run: |
          mvn gitflow:release-finish
